export const PROFILE= {
    FETCH_PROFILE_REQUEST:'FETCH_PROFILE_REQUEST',
    FETCH_PROFILE_REQUEST_SUCCESS:'FETCH_PROFILE_REQUEST_SUCCESS',
    FETCH_PROFILE_REQUEST_FAILURE:'FETCH_PROFILE_REQUEST_FAILURE',
    FETCH_SALES_REP_REQUEST:'FETCH_SALES_REP_REQUEST',
    FETCH_SALES_REP_SUCCESS:'FETCH_SALES_REP_SUCCESS',
    FETCH_SALES_REP_FAILURE:'FETCH_SALES_REP_FAILURE',
    FETCH_CUST_REQUEST:'FETCH_CUST_REQUEST',
    FETCH_CUST_REQUEST_SUCCESS:'FETCH_CUST_REQUEST_SUCCESS',
    FETCH_CUST_REQUEST_FAILURE:'FETCH_CUST_REQUEST_FAILURE',
    LOGOUT: 'LOGOUT'
}